### ISSUE TITLE
Server returning timeout immediately after sending make your move message

### ISSUE THREAD

**Issue by gaboth22** [MatthewBregg/TigerIsland#43]
![pasted image at 2017_04_12 02_11 am](https://cloud.githubusercontent.com/assets/7754526/24944264/647b8a42-1f28-11e7-8322-3d9d64aefa23.png)

**Comment by wylieallen** [comment]
I ran a couple four client test tournaments using commit https://github.com/MatthewBregg/TigerIsland/commit/0497d1b2b2ce31224998d8122509518821d7c0a3 and ran into this issue too.

Here's a server log: https://pastebin.com/egZGLQvX

Here's Player 2's client output at the time of the timeout at line 268:

Server: GAME B MOVE 2 PLAYER 3 PLACED GRASS+GRASS AT 5 -2 -3 2 FOUNDED SETTLEMENT AT 2 -1 -1
Message parsed as move by parser 1 with game B and player id 2
Parsing buildaction as villager placement
Server: GAME A MOVE 2 PLAYER 2 PLACED GRASS+GRASS AT -3 0 3 2 FOUNDED SETTLEMENT AT -2 0 2
Server: MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 2 PLACE LAKE+LAKE
Message parsed as move by parser 2 with game A and player id 2
Server: GAME B MOVE 2 PLAYER 2 FORFEITED: TIMEOUT
Message parsed as move prompt
Server: GAME A MOVE 2 PLAYER 3 PLACED LAKE+LAKE AT 5 -2 -3 3 FOUNDED SETTLEMENT AT 1 1 -2
Sending: GAME B MOVE 2 PLACE LAKE+LAKE AT 6 -1 -5 6 FOUND SETTLEMENT AT 6 -5 -1
Server: MAKE YOUR MOVE IN GAME A WITHIN 1.5 SECONDS: MOVE 3 PLACE ROCK+ROCK
Total time: 267

So our client measured the total time elapsed as just 267 milliseconds.

**Comment by wylieallen** [comment]
It just happened to me in a 1v1 tournament, too, with lots of weird buggy behavior afterwards. Posting it here because it all appears to be related to this instant timeout bug.

Server log: https://pastebin.com/VyAWXhQR

Player 2 gets an instant timeout in Game A at line 401. Player 2's move for Game A arrives at line 415, and is interpreted by the server as a malformed move. 

Some more buggy behavior that occurs after the timeout:

**SENDING MESSAGE TO 2: "MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 9 PLACE LAKE+GRASS"**
Scoreboard : P1 1 P2 2 GAME A OVER PLAYER 2 FORFEITED PLAYER 1 WIN
Logger: Game Id: 0 Challenge Id: 0 Match ID : 0 Turn Number 18 ::GAME A OVER PLAYER 2 FORFEITED PLAYER 1 WIN Winner 1 Loser 2
CLIENT 2: GAME A MOVE 8 PLACE GRASS+LAKE AT 5 -7 2 2 FOUND SETTLEMENT AT -2 3 -1
SENDING MESSAGE TO 2: "GAME A MOVE 8 PLAYER 2 FORFEITED: MALFORMED MOVE"
SENDING MESSAGE TO 1: "GAME A MOVE 8 PLAYER 2 FORFEITED: MALFORMED MOVE"
Logger: Game Id: 1 Challenge Id: 0 Match ID : 0 Turn Number 18 :: Turn has ended

// Message says Game A, but the server seems to interpret Client 2's move as a malformed input for Game B...

// Client 1 is then prompted for its next move in Game B even though Client 2 still hasn't sent its real move for Game B yet:

**SENDING MESSAGE TO 1: "MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 9 PLACE ROCK+JUNGLE"**
**CLIENT 1: GAME B MOVE 9 PLACE ROCK+JUNGLE AT -4 6 -2 1 FOUND SETTLEMENT AT -5 1 4**
...
SENDING MESSAGE TO 2: "GAME B MOVE 9 PLAYER 1 PLACED ROCK+JUNGLE AT -4 6 -2 1 FOUNDED SETTLEMENT AT -5 1 4"
SENDING MESSAGE TO 1: "GAME B MOVE 9 PLAYER 1 PLACED ROCK+JUNGLE AT -4 6 -2 1 FOUNDED SETTLEMENT AT -5 1 4"
Logger: Game Id: 1 Challenge Id: 0 Match ID : 0 Turn Number 19 :: Turn has ended
SENDING MESSAGE TO 2: "MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 10 PLACE JUNGLE+GRASS"

// Client 2 finally sends its actual move for Game B Move 9 (the one for which server misinterpreted its Game A message as an input), but it's interpreted as another malformed move:
 
**CLIENT 2: GAME B MOVE 9 PLACE LAKE+GRASS AT -1 7 -6 5 FOUND SETTLEMENT AT -5 1 4**
SENDING MESSAGE TO 2: "GAME B MOVE 9 PLAYER 2 FORFEITED: MALFORMED MOVE"
SENDING MESSAGE TO 1: "GAME B MOVE 9 PLAYER 2 FORFEITED: MALFORMED MOVE"
Logger: Game Id: 1 Challenge Id: 0 Match ID : 0 Turn Number 20 :: Turn has ended

// Despite malformed move forfeit message, server prompts Client 1 for another move, which it then interprets as an illegal tile placement:

SENDING MESSAGE TO 1: "MAKE YOUR MOVE IN GAME B WITHIN 1.5 SECONDS: MOVE 10 PLACE ROCK+JUNGLE"
CLIENT 1: GAME B MOVE 10 PLACE ROCK+JUNGLE AT -1 1 0 6 FOUND SETTLEMENT AT -1 0 1
SENDING MESSAGE TO 2: "GAME B MOVE 10 PLAYER 1 FORFEITED: ILLEGAL TILE PLACEMENT"
SENDING MESSAGE TO 1: "GAME B MOVE 10 PLAYER 1 FORFEITED: ILLEGAL TILE PLACEMENT"

**Comment by MatthewBregg** [comment]
What commit were you on when this happened?

**Comment by thephil16** [comment]
Made changes to player message queuing. Please test issue with branch [https://github.com/MatthewBregg/TigerIsland/tree/InstantTimeoutIssue](url)

**Comment by MatthewBregg** [comment]
https://pastebin.com/mqT0mHc6
I ran the game with  https://pastebin.com/VyAWXhQR, and did not encounter this issue.
In this log, the game ends because I wasn't sure what move to make after the game in the log crashed. 
Closing, reopen if you are still concerned.
